### ISSUE TITLE
[Migration] Migrate erc-4906 Smart Contract from Cairo 0.10 to Cairo 1

### ISSUE THREAD

**Issue by bal7hazar** [carbonable-labs/cairo0-erc-4906#3]
# Description

The [ERC-4906](https://eips.ethereum.org/EIPS/eip-4906) is writing in Cairo 0.10 and it is working. 

# Tasks

The Tasks are : 
- [ ] Migrate the `src/erc4906` from Cairo 0.10 to Cairo 1 (preset, constants, library)
- [ ] Migrate the tests
- [ ] Add tests to migrate an ERC-4906 Smart Contract from Cairo 0.10 to Cairo 1

**Comment by stevencartavia** [comment]
Hi, I would like to try this!
